<!doctype html>
<html lang="zh-CN">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, inital-scale" />
      <title>全新世界</title>
    </head>
    <body style="margin: 0;">
        <div style="
            background-color: aliceblue;
            text-align: center;
            padding: 40px;
            "
            >
            <img alt="头像"src="https://p3.ssl.qhimgs1.com/sdr/400__/t01c33b4901fd6e3573.jpg" width="120PX" height="120PX">
        </div>
        <div style="
        max-width: 760px;
        margin: 30px auto;
        padding: 15px;
        line-height: 1.7;
        ">
        <p>突然发现,我也还是很厉害的，三四个小时就给你熬出来了，希望后边的课程也能快速上手
                                  再次感谢up主
        </p>
        <p></p>
        </div>
        <div style="
          background-color: blue;
          text-align: center;
          padding: 40px;
          font-size: 12px;
          "
          >      
          <p>版权所有： yangzhiuwei.com</p>
          <a href="https://yangzhiuwei.com">我的网站</a>
